<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../Chess.Server.Application/Chess.Server.Application.csproj" />
    <ProjectReference Include="../Chess.ServiceDefaults/Chess.ServiceDefaults.csproj" />
    <ProjectReference Include="../Chess.Server.Akka/Chess.Server.Akka.csproj" />
    <ProjectReference Include="../Chess.Server.Orleans/Chess.Server.Orleans.csproj" />
  </ItemGroup>
</Project>
