<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="Microsoft.Playwright" />
    <ProjectReference Include="../../clients/Chess.Web/Chess.Web.csproj" />
  </ItemGroup>
</Project>
